### PR TITLE
Added web-prod-app-insights-alerts

### PR DESCRIPTION
**Pull request by MikeLarah**

### CODE REVIEW

**Comment by HowardvanRooijen** [comment]
So how could you set up multiple alerts? We can define different KQL queries, different time windows, but how do you orchestrate them together?

**Comment by MikeLarah** [comment]
You would do it in the orchestrating script. So you could define the alert properties in an array variable/parameter and then loop through, e.g.
```bicep
var alerts = [
  {
    name: 'AlertOn500s'
    query: 'requests\n| where resultCode == 500\n| count'
    operator: 'GreaterThan'
    //...
  }
  {
    name: 'AlertOn400s'
    query: 'requests\n| where resultCode == 400\n| count'
    operator: 'GreaterThan'
    //...
  }
]

module appinsightsalert 'br:foo.azurecr.io/bicep/general/app-insights-alerts:0.1.1' = [for alert in alerts: {
  name: alert.name
  params: {
    alertName: alert.name
    query: alert.query
    operator: alert.operation
    //...
  }
}]
```

I still struggle to see what the module adds in this case

**Comment by MikeLarah** [comment]
What might be better is to have an optional `alerts` object array you can pass into our existing `app-insights` module. But the fact that you can't have strongly-typed object parameters in Bicep makes it quite brittle.

**Comment by ElisendaGascon** [comment]
Created an opinionated web-prod-app-insights-alerts module and removed the generic app-insights-alert module.

**Review by JamesDawson — APPROVED** [review]

**Review by JamesDawson — APPROVED** [review]

**Pull request merged**
